//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace So_Do_Tu_Duy.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DRAWOBJ
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DRAWOBJ()
        {
            this.DRAWOBJ1 = new HashSet<DRAWOBJ>();
        }
    
        public int idObj { get; set; }
        public int idParent { get; set; }
        public int idProject { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DRAWOBJ> DRAWOBJ1 { get; set; }
        public virtual DRAWOBJ DRAWOBJ2 { get; set; }
        public virtual PROJECT PROJECT { get; set; }
    }
}
