//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace So_Do_Tu_Duy.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shape
    {
        public int ID { get; set; }
        public string NameShape { get; set; }
        public double LocationX { get; set; }
        public Nullable<double> Witdh { get; set; }
        public Nullable<double> Height { get; set; }
        public string Descripton { get; set; }
        public int IDPro { get; set; }
        public Nullable<double> LocationY { get; set; }
    
        public virtual ProjectShape ProjectShape { get; set; }
    }
}
